server:
  port: 80
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/alpha?characterEncoding=UTF-8&serverTimezone=UTC&&autoReconnection=true
    url: jdbc:log4jdbc:mysql://133.186.217.231:3306/alpha?characterEncoding=UTF-8&serverTimezone=UTC&&autoReconnection=true
    username: alpha.manager
    password: iammax1!
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

