server:
  port: 4040
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alpha?characterEncoding=UTF-8&serverTimezone=UTC&&autoReconnection=true
    username: alpha.manager
    password: iammax1!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
